# Generated by Django 2.2.8 on 2020-01-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighbour',
        ),
    ]
