# Generated by Django 2.2.8 on 2020-01-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0008_health_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post/'),
        ),
        migrations.AddField(
            model_name='police',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post/'),
        ),
    ]
